ALTER TABLE "students"
ADD COLUMN IF NOT EXISTS "level" INTEGER;

ALTER TABLE "payments"
ADD COLUMN IF NOT EXISTS "object_path" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "slip_url" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "uploaded_by_user_id" INTEGER;